### ISSUE TITLE
cannot run demo.android

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/nativescript-plugin-seed#104]
Hello,

I am trying to follow this guide: https://docs.nativescript.org/plugins/building-plugins

When I get to the point to run the demo, I get the following error:
```
Successfully synced application org.nativescript.demo on device cbfbe126.
System.err: android.content.res.Resources$NotFoundException: Resource ID #0xfffffff6
System.err:     at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:202)
System.err:     at android.content.res.Resources.loadXmlResourceParser(Resources.java:2968)
System.err:     at android.content.res.Resources.getAnimation(Resources.java:2008)
System.err:     at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:75)
System.err:     at android.support.v4.app.FragmentManagerImpl.loadAnimation(FragmentManager.java:1102)
System.err:     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1600)
System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1641)
System.err:     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:794)
System.err:     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
System.err:     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2200)
System.err:     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2153)
System.err:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2063)
System.err:     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:725)
System.err:     at android.os.Handler.handleCallback(Handler.java:751)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6688)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

After looking at the package.json, I noticed that it points to v 5.0.0:
```
"nativescript": {
        "platforms": {
            "android": "5.0.0",
            "ios": "5.0.0"
        }
    },
```
My system is not ready to be upgraded to version 5.0.0.  Is there a way to use the seed project with version 4.2.*?  If so, what step do I need to take to do that?

**Comment by dpdragnev** [comment]
Never mind.  I updated my system and everything is working as expected. :)
