### ISSUE TITLE
file.ts Missing from Typescript compilation

### ISSUE THREAD

**Issue by blaur** [NativeScript/nativescript-plugin-seed#144]
I've used the seed to initiate a new plugin but I've running into issues when running my demo.

I can successfully build the demo but when running the app and trying to initiate a class from my new plugin I'm getting following error:
`JS: ERROR TypeError: nativescript_angular_mobilepay_1.MobilePay is not a constructor`

It is a very simple plugin consting of:
- index.d.ts
- mobilepay.android.ts
- mobilepay.ios.ts
- mobilepay.common.ts

Index.d.ts:
```
export declare class MobilePay {
    createMobilePayInstance(merchantId: string): any;

    isMobilePayInstalled(merchantId: string): boolean;

    MakePayment(merchantId: string, price: number, accountId: string): any;
}
```

mobilepay-common.ts
```
export abstract class MobilePayBase {
    public abstract createMobilePayInstance(merchantId: string): any;
    public abstract isMobilePayInstalled(merchantId: string): boolean;
    public abstract MakePayment(merchantId: string, price: number, accountId: string): void;
}

```
mobilepay.android.ts
```
import {
    MobilePayBase
} from './mobilepay-common';


export class MobilePay extends MobilePayBase{

    private static MOBILEPAY_PAYMENT_REQUEST_CODE = 1337;

    createMobilePayInstance(merchantId: string): any {
        ...................
    }

    isMobilePayInstalled(merchantId: string): boolean {
        .............
    }

    MakePayment(merchantId: string, price: number, accountId: string): void {
       ..............
    }

}
```

If trying to use --bundle, I'm seeing the following:
```
ERROR in C:/Users/bbl/Desktop/Brian/Development/nativescript-angular-mobilepay/src/mobilepay.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\bbl\Desktop\Brian\Development\nativescript-angular-mobilepay\src\mobilepay.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\bbl\Desktop\Brian\Development\nativescript-angular-mobilepay\demo-angular\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:752:23)
    at plugin.done.then (C:\Users\bbl\Desktop\Brian\Development\nativescript-angular-mobilepay\demo-angular\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 @ ./app/item/items.component.ts 2:0-59 13:28-37
 @ ./app/app.module.ts
 @ ./main.ts
Webpack compilation complete.
Executing webpack failed with exit code 2.
```

Any good suggestions?

**Comment by VladimirAmiorkov** [comment]
Hi @blaur ,

I tried to reproduce the describe issue but to no avail. After executing `tns plugin create my-plugin` and following the prompts to create TypeScript and Angular demo apps I was able to replace the class in the `.common.ts` file with the snippet you provided. After running `npm run demo.ios` the app started correctly with no errors.

I am attaching my test plugin to my response, can you take a look at it and let me know if you an reproduce the issue in that project.
[my-plugin.zip](https://github.com/NativeScript/nativescript-plugin-seed/files/3236638/my-plugin.zip)

**Comment by blaur** [comment]
@VladimirAmiorkov I've just reinstalled all from node to tns and then cloned the seed again. Now everything works.

Apologies for wasting your time and **thanks** for your feedback.

**Comment by blaur** [comment]
@VladimirAmiorkov I'm getting this error now again after using the new workflow. If setting this: 
`"useLegacyWorkflow": false`

Then I'm getting this error again where mobilepay.ts is not present:
```
ERROR in /Users/brianbaklaursen/Development/Drivelogger/nativescript-mobilepay/src/mobilepay.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: /Users/brianbaklaursen/Development/Drivelogger/nativescript-mobilepay/src/mobilepay.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
```

**Comment by VladimirAmiorkov** [comment]
Can you give us more details when exactly you are getting this error, when running one of the apps or when doing `tsc` inside the src directory or something totally different. It looks like you have not added the src files to a tsconfig.json, probably in one of the demo apps. By design the plugin seed updates those files when you run its postclone script, check your demo apps tsconfig.json files they should contains an include and exclude that looks like this:

```
"exclude": [
	"node_modules",
	"platforms",
	"../src/node_modules"
],
"include": [
	"../src",
	"**/*"
]
```

**Comment by blaur** [comment]
Thanks for the fast reply. 

I'm am seeing this when running _npm run demo-angular.ios_ and **only** when  _"useLegacyWorkflow": false._ is set in nsconfig.

When the legacy workflow is true then everything is working perfectly. As said, this is a direct clone where I've followed all steps as per your readme from 2-3 months back.

My tsconfig for the demo-angular app looks like this:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "lib": [
            "es6",
            "dom",
            "es2015.iterable"
        ],
        "baseUrl": ".",
        "paths": {
            "~/*": [
                "src/*"
            ],
            "*": [
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "platforms",
        "../src/node_modules"
    ],
    "include": [
        "../src",
        "**/*"
    ]
}
```

and my nsconfig:
```
{
  "appResourcesPath": "App_Resources",
  "appPath": "src",
  "useLegacyWorkflow": true
}
```

**Comment by VladimirAmiorkov** [comment]
I assume you are using NativeScript CLI 5.x.x because `useLegacyWorkflow` has been removed completely in 6.0.0, right? The current plugin seed has been updated to work only with NativeScript 6.0.0 . Can you upgrade your NativeScript to 6.0.0 and see if that changes this issue. Also a good troubleshooting start is to clone the current plugin seen somewhere on your machine and see if that works on it, after that investigate how your structure has diverged from the current one.

If you can send us your plugin so we can take a look at it it would be of great help.

**Comment by elena-p** [comment]
closing due to inactivity
