### ISSUE TITLE
Building freshly cloned seed gets 'AAPT: error: resource drawable/icon not found'

### ISSUE THREAD

**Issue by yonghongren** [NativeScript/nativescript-plugin-seed#73]
Cloned the seed project, and the build fails: 

```
Gradle build...
         + applying user-defined configuration from /home/ren/tmp/nativescript-plugin-test/demo/app/App_Resources/Android/app.gradle
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
Configuration 'debugCompile' in project ':app' is deprecated. Use 'debugImplementation' instead.
         + adding nativescript runtime package dependency: nativescript-optimized
         + adding aar plugin dependency: /home/ren/tmp/nativescript-plugin-test/demo/node_modules/tns-core-modules-widgets/platforms/android/widgets-release.aar
/home/ren/tmp/nativescript-plugin-test/demo/platforms/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:23: AAPT: error: resource drawable/icon (aka org.nativescript.demo:drawable/icon) not found.
    
/home/ren/tmp/nativescript-plugin-test/demo/platforms/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:23: error: resource drawable/icon (aka org.nativescript.demo:drawable/icon) not found.
error: failed processing manifest.

Failed to execute aapt
com.android.ide.common.process.ProcessException: Failed to execute aapt
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:796)
        at com.android.build.gradle.tasks.ProcessAndroidResources.invokeAaptForSplit(ProcessAndroidResources.java:551)
        at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:285)
```
So it looks the build is looking the non-existent icons. Copying some drawable png files into the expected directory gets the build to pass. But I suspect I missed something basic. I did follow the instructions to the letter.

TNS version: 3.4.1
Android SDK build tool version: 26.1.1
npm: 5.6.1

Appreciate any suggestions.

**Comment by tgpetrov** [comment]
Hi @yonghongren,

The demo application that you are trying to run is updated with [4.0 version](https://www.nativescript.org/blog/nativescript-4.0-is-out) of NativeScript. You need to install the latest version of NativeScript in order to be able to run the app:
```
npm install -g nativescript@latest
```

**Comment by yonghongren** [comment]
Hi @tgpetrov,

Indeed that's the issue. Now it builds fine. Thank you!
